### ISSUE TITLE
Script for getting all WQ parameters of interest from NWIS

### ISSUE THREAD

**Issue by cahhansen** [spence97/Low_Flows#7]
Using dataRetrieval package in R
For sure: Temperature, Dissolved Oxygen, (any others that night be linked). Can look up the parameter codes: [here](https://nwis.waterdata.usgs.gov/usa/nwis/pmcodes?radio_pm_search=param_group&pm_group=All+--+include+all+parameter+groups&pm_search=&casrn_search=&srsname_search=&format=html_table&show=parameter_group_nm&show=parameter_nm&show=casrn&show=srsname&show=parameter_units) 

Output to .csv or an Rdata file that can be ingested in a data/statistical modeling script.
Make generalizable so it can get data for whatever region we end up doing.

**Comment by jshafiei** [comment]
Water Quantity (i.e discharge) data is quite available for most stations (Check the code, I put in the <> code), based on hourly and daily since ~ 1930 (and even earlier for many stations). However, Water quality data have the following issues:
1-The data is not available for all stations.
2-The record of water quality data for gauges is irregular. Different time steps, different sampling hour and etc.
3-There are some gaps in the available data for some stations (and it is hard to ignore these gaps, if trend or correlation is important for us).

**Comment by jread-usgs** [comment]
Let us know at USGS if you want any help working on accessing or standardizing these data. Also, a paper that may be of interest: onlinelibrary.wiley.com/doi/10.1002/2016WR019993/full

**Comment by cahhansen** [comment]
Update: We've since narrowed down the gages/reaches of interest (now only 3 in CA and 1 in AL) and parameters to temperature for demonstration in this project and it looks like temperature data (in some form) is currently available near all of these reaches.
